# Your Solution
version: '3'

services:
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://subhash:aPq2iAeJ4BYojsB5T0GYWC0Rb6KUTYJd@dpg-crciq7aj1k6c73cmu3g0-a.oregon-postgres.render.com/db_8ml0

  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management  
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgresql://subhash:aPq2iAeJ4BYojsB5T0GYWC0Rb6KUTYJd@dpg-crciq7aj1k6c73cmu3g0-a.oregon-postgres.render.com/db_8ml0